apiVersion: v1
kind: Service
metadata:
  name: playwright-tests
  namespace: qa-automation
  labels:
    app: playwright-tests
    tier: testing
spec:
  type: ClusterIP
  selector:
    app: playwright-tests
  ports:
  - name: http
    port: 80
    targetPort: 3333
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: report-server
  namespace: qa-automation
  labels:
    app: report-server
    tier: testing
spec:
  type: LoadBalancer
  selector:
    app: report-server
  ports:
  - name: http
    port: 80
    targetPort: 3333
    protocol: TCP
  sessionAffinity: ClientIP
